[project]
name = "dev-type"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyside6>=6.10.0",
    "pytest>=8.4.2",
    "pyinstaller>=6.0.0",
    "pillow>=10.0.0",
    "matplotlib>=3.10.8",
]
